### ISSUE TITLE
potential dc template

### ISSUE THREAD

**Issue by patricksimonian** [Work-Webteam/atWork#1]
```yaml
kind: Template
apiVersion: v1
objects:
  - apiVersion: v1
    kind: Service
    spec:
      ports:
        - name: 8080-tcp
          port: 8080
          protocol: TCP
          targetPort: 8080
      selector:
        deploymentconfig: atwork-apache
      sessionAffinity: None
      type: ClusterIP
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftWebConsole
      labels:
        app: atwork-apache
      name: atwork-apache
  - apiVersion: autoscaling/v1
    kind: HorizontalPodAutoscaler
    spec:
      maxReplicas: 5
      minReplicas: 1
      scaleTargetRef:
        apiVersion: v1
        kind: DeploymentConfig
        name: atwork-apache
      targetCPUUtilizationPercentage: 80
    metadata:
      annotations:
        autoscaling.alpha.kubernetes.io/conditions: >-
          [{"type":"AbleToScale","status":"True","lastTransitionTime":"2020-03-11T23:33:50Z","reason":"ReadyForNewScale","message":"the
          last scale time was sufficiently old as to warrant a new
          scale"},{"type":"ScalingActive","status":"True","lastTransitionTime":"2020-03-17T17:19:43Z","reason":"ValidMetricFound","message":"the
          HPA was able to successfully calculate a replica count from cpu
          resource utilization (percentage of
          request)"},{"type":"ScalingLimited","status":"True","lastTransitionTime":"2020-03-17T17:15:48Z","reason":"TooFewReplicas","message":"the
          desired replica count is increasing faster than the maximum scale
          rate"}]
        autoscaling.alpha.kubernetes.io/current-metrics: >-
          [{"type":"Resource","resource":{"name":"cpu","currentAverageUtilization":0,"currentAverageValue":"0"}}]
      labels:
        app: atwork-apache
      name: atwork-apache
  - apiVersion: apps.openshift.io/v1
    kind: DeploymentConfig
    spec:
      replicas: 1
      selector:
        app: atwork-apache
        deploymentconfig: atwork-apache
      strategy:
        activeDeadlineSeconds: 21600
        resources: {}
        rollingParams:
          intervalSeconds: 1
          maxSurge: 25%
          maxUnavailable: 25%
          timeoutSeconds: 600
          updatePeriodSeconds: 1
        type: Rolling
      template:
        metadata:
          annotations:
            openshift.io/generated-by: OpenShiftWebConsole
          creationTimestamp: null
          labels:
            app: atwork-apache
            deploymentconfig: atwork-apache
        spec:
          containers:
            - env:
                - name: ATWORK_DB_HOST
                  value: atworkdb.whamor-test.svc.cluster.local
                - name: ATWORK_DB_USER
                  valueFrom:
                    secretKeyRef:
                      key: database-user
                      name: atworkdb
                - name: ATWORK_DB
                  valueFrom:
                    secretKeyRef:
                      key: database-name
                      name: atworkdb
                - name: ATWORK_DB_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      key: database-password
                      name: atworkdb
                - name: ATWORK_HASH_SALT
                  value: N6j8GtSRsuZp5YJJ3RNXybPKgpUSdhfB
              image: >-
                docker.io/jeremyvernon/atwork-apache@sha256:2ead8e4b07cccc1031893c3d2c581eaabcc0775eff7420b5b3abfb02b7f9d43f
              imagePullPolicy: Always
              name: atwork-apache
              ports:
                - containerPort: 8080
                  protocol: TCP
              resources:
                requests:
                  cpu: 350m
                  memory: 700Mb
                limits:
                  cpu: 400m
                  memory: 1Gb
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
              volumeMounts:
                - mountPath: /var/www/html
                  name: volume-n0eaq
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
          volumes:
            - name: volume-n0eaq
              persistentVolumeClaim:
                claimName: atwork-storage
      test: false
      triggers:
        - type: ConfigChange
        - imageChangeParams:
            automatic: true
            containerNames:
              - atwork-apache
            from:
              kind: ImageStreamTag
              name: 'atwork-apache:test'
              namespace: whamor-test
            lastTriggeredImage: >-
              docker.io/jeremyvernon/atwork-apache@sha256:2ead8e4b07cccc1031893c3d2c581eaabcc0775eff7420b5b3abfb02b7f9d43f
          type: ImageChange
    metadata:
      annotations:
        openshift.io/generated-by: OpenShiftWebConsole
      generation: 16
      labels:
        app: atwork-apache
      name: atwork-apache
  - apiVersion: image.openshift.io/v1
    kind: ImageStream
    spec:
      lookupPolicy:
        local: false
      tags:
        - annotations:
            openshift.io/generated-by: OpenShiftWebConsole
            openshift.io/imported-from: docker.io/jeremyvernon/atwork-apache
          from:
            kind: DockerImage
            name: docker.io/jeremyvernon/atwork-apache
          generation: 2
          importPolicy: {}
          name: latest
          referencePolicy:
            type: Source
    metadata:
      annotations:
        openshift.io/image.dockerRepositoryCheck: 2020-03-11T18:14:31.000Z
      generation: 2
      labels:
        app: atwork-apache
      name: atwork-apache
  - apiVersion: route.openshift.io/v1
    kind: Route
    spec:
      host: atwork-test-whamor-test.pathfinder.gov.bc.ca
      path: /
      port:
        targetPort: 8080-tcp
      to:
        kind: Service
        name: atwork-apache
        weight: 100
      wildcardPolicy: None
    metadata:
      annotations:
        openshift.io/host.generated: 'true'
      labels:
        app: atwork-apache
      name: atwork-test
```
